spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test_class?createDatabaseIfNotExist=true
    password: Danidu#678@mysql
  application:
    name: demo
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

data:
  customer:
    id: kalana